# Generated by Django 6.0.5 on 2026-05-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_task_comment_alter_task_date_alter_task_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleevent',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ScheduleEvent',
        ),
    ]
