# Generated by Django 6.0.5 on 2026-05-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_task_description_remove_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
