# Generated by Django 6.0.5 on 2026-05-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10),
        ),
    ]
