# Generated by Django 6.0.5 on 2026-05-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_task_description_task_title_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
